DROP TABLE IF EXISTS sales;

CREATE TABLE sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_cliente INT NOT NULL,
    producto VARCHAR(100) NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DOUBLE NOT NULL
);

INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (1, 'Luz LED escritorio', 2, 286.16);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (1, 'Cámara de seguridad', 4, 1173.49);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (1, 'Memoria RAM 16GB', 2, 706.42);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (1, 'Mouse Pad XL', 2, 43.98);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (1, 'Joystick USB', 1, 1306.48);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (1, 'Adaptador Bluetooth', 5, 1447.5);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (2, 'Silla Ergonómica', 3, 401.85);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (2, 'Monitor Samsung', 3, 1398.81);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (2, 'Pantalla Táctil 15"', 4, 834.28);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (2, 'Joystick USB', 4, 780.5);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (2, 'Control Xbox', 5, 627.03);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (2, 'Memoria RAM 16GB', 4, 264.52);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (3, 'Memoria RAM 16GB', 1, 1233.15);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (3, 'Adaptador Bluetooth', 3, 133.96);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (4, 'Laptop Lenovo', 5, 65.5);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (4, 'Pantalla Táctil 15"', 3, 437.75);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (4, 'Mouse Pad XL', 3, 768.55);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (4, 'Software Antivirus', 2, 257.41);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (4, 'Repetidor WiFi', 1, 1302.37);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (4, 'Auriculares Sony', 3, 774.23);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (5, 'Consola Nintendo Switch', 3, 817.25);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (5, 'Kit herramientas PC', 5, 36.24);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (5, 'Impresora HP', 1, 296.37);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (6, 'Mouse Pad XL', 2, 1308.83);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (6, 'Combo Teclado + Mouse', 2, 1256.46);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (6, 'Monitor LG UltraWide', 3, 927.85);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (7, 'Tablet gráfica', 1, 192.52);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (8, 'Disco Duro Externo 1TB', 4, 415.89);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (8, 'Pantalla Táctil 15"', 2, 91.96);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (8, 'Mouse Logitech', 2, 296.74);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (9, 'Laptop Lenovo', 5, 435.98);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (9, 'Cooler para CPU', 5, 1193.38);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (10, 'PC Gamer', 1, 1253.39);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (10, 'Teclado Mecánico', 4, 523.15);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (10, 'Mouse Pad XL', 5, 1370.27);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (10, 'Fuente de poder 600W', 5, 975.55);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (11, 'Memoria RAM 16GB', 2, 1199.44);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (11, 'Impresora HP', 5, 147.14);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (11, 'Batería Externa', 1, 407.34);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (11, 'Monitor Samsung', 1, 1123.89);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (12, 'Mouse Logitech', 1, 67.96);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (12, 'Lector de tarjetas SD', 3, 454.71);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (12, 'Silla Ergonómica', 3, 315.9);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (12, 'Webcam HD', 5, 974.51);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (13, 'Pantalla Táctil 15"', 2, 271.14);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (13, 'Control Xbox', 3, 945.7);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (13, 'Tablet gráfica', 3, 561.6);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (13, 'Software Antivirus', 3, 1353.02);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (14, 'Control Xbox', 3, 1411.2);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (14, 'Tablet gráfica', 4, 1260.0);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (14, 'Monitor Samsung', 3, 1117.53);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (14, 'Ventilador gabinete', 2, 758.52);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (14, 'Batería Externa', 3, 1255.72);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (14, 'Cámara de seguridad', 1, 1480.29);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (15, 'Adaptador Bluetooth', 2, 552.13);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (16, 'Luz LED escritorio', 1, 85.2);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (16, 'Switch de red 8 puertos', 3, 1039.26);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (16, 'Luz LED escritorio', 2, 906.19);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (16, 'Repetidor WiFi', 4, 420.02);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (16, 'Kit herramientas PC', 2, 295.33);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (17, 'Pasta térmica', 1, 348.54);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (18, 'Lector de tarjetas SD', 3, 1434.82);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (18, 'Mini proyector', 3, 1482.02);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (18, 'Joystick USB', 4, 562.69);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (19, 'Cámara de seguridad', 2, 1270.73);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (20, 'Hub USB 3.0', 1, 282.94);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (20, 'Memoria RAM 16GB', 2, 349.06);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (20, 'Silla Ergonómica', 2, 1449.75);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (20, 'Cargador USB-C', 1, 737.12);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (21, 'Impresora HP', 2, 1489.12);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (21, 'Tarjeta gráfica RTX 3060', 5, 1017.52);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (21, 'Monitor Samsung', 2, 1150.11);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (21, 'Teclado Mecánico', 2, 549.51);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (22, 'Combo Teclado + Mouse', 5, 1275.36);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (23, 'Soporte Monitor', 3, 148.91);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (23, 'Tablet gráfica', 3, 301.04);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (23, 'Teclado inalámbrico', 1, 920.83);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (24, 'Software Antivirus', 1, 1056.7);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (24, 'Impresora HP', 3, 683.96);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (24, 'Mini proyector', 5, 39.55);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (25, 'Mouse Logitech', 3, 1478.82);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (25, 'Combo Teclado + Mouse', 2, 1441.23);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (25, 'Tablet Huawei', 2, 581.3);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (26, 'Mini proyector', 3, 558.81);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (26, 'Ventilador gabinete', 2, 366.05);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (26, 'Webcam HD', 5, 1215.36);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (26, 'Smartphone Xiaomi', 1, 145.43);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (26, 'Cooler para CPU', 1, 1125.02);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (26, 'Disco SSD 512GB', 1, 248.93);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (27, 'Tablet gráfica', 2, 441.2);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (28, 'Lector de tarjetas SD', 3, 108.87);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (29, 'Silla Ergonómica', 3, 194.47);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (29, 'Control Xbox', 3, 220.88);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (29, 'Smartphone Xiaomi', 5, 1074.45);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (29, 'PC Gamer', 5, 897.06);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (29, 'Soporte para Laptop', 2, 901.5);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (29, 'Smartphone Xiaomi', 1, 1486.82);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (30, 'Pasta térmica', 3, 1237.35);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (30, 'Teclado inalámbrico', 2, 1040.98);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (30, 'Hub USB 3.0', 1, 1300.82);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (30, 'Disco Duro Externo 1TB', 1, 867.0);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (30, 'Cable Ethernet 10m', 1, 1170.72);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (31, 'Software Antivirus', 3, 522.24);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (31, 'Pantalla Táctil 15"', 1, 233.33);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (31, 'Kit herramientas PC', 3, 131.07);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (32, 'Mouse Pad XL', 3, 129.73);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (32, 'Router TP-Link', 4, 856.31);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (32, 'Ventilador gabinete', 5, 774.68);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (32, 'Luz LED escritorio', 2, 235.57);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (32, 'Filtro de pantalla', 1, 1260.66);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (32, 'Cámara de seguridad', 1, 1399.94);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (33, 'Joystick USB', 3, 547.06);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (33, 'Repetidor WiFi', 3, 1243.02);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (33, 'Teclado Mecánico', 1, 1394.05);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (33, 'Auriculares Sony', 5, 146.22);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (33, 'Switch de red 8 puertos', 1, 624.65);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (34, 'PC Gamer', 4, 445.72);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (34, 'Hub USB 3.0', 1, 615.77);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (34, 'SSD NVMe 1TB', 2, 635.57);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (34, 'Lector de tarjetas SD', 4, 289.42);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (34, 'Joystick USB', 4, 540.75);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (34, 'Batería Externa', 1, 270.38);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (35, 'Router TP-Link', 5, 395.43);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (35, 'Pasta térmica', 1, 206.47);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (35, 'Batería Externa', 2, 703.54);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (36, 'Router TP-Link', 2, 449.35);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (36, 'Disco Duro Externo 1TB', 1, 1387.49);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (36, 'Router TP-Link', 2, 540.14);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (36, 'Tablet gráfica', 4, 679.66);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (36, 'Tablet Huawei', 2, 1376.96);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (36, 'Filtro de pantalla', 4, 144.8);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (37, 'Filtro de pantalla', 1, 1434.73);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (37, 'Joystick USB', 4, 1226.76);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (37, 'Estabilizador de voltaje', 3, 97.56);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (37, 'Kit herramientas PC', 3, 931.28);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (37, 'Mouse Pad XL', 3, 109.86);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (38, 'PC Gamer', 4, 286.52);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (39, 'Disco Duro Externo 1TB', 5, 471.98);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (39, 'Combo Teclado + Mouse', 5, 94.87);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (40, 'Teclado inalámbrico', 1, 654.6);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (40, 'Tablet Huawei', 4, 1158.98);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (40, 'Laptop Lenovo', 3, 298.36);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (40, 'Switch de red 8 puertos', 1, 189.9);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (40, 'Smartphone Xiaomi', 5, 636.72);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (41, 'Soporte para Laptop', 5, 776.04);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (41, 'Joystick USB', 2, 574.7);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (41, 'Cable HDMI', 5, 1139.34);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (41, 'Software Antivirus', 3, 994.35);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (42, 'Altavoces JBL', 1, 573.94);
INSERT INTO sales (id_cliente, producto, cantidad, precio_unitario) VALUES (42, 'Monitor LG UltraWide', 1, 539.3);


